# Generated by Django 4.2.11 on 2024-05-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_comment_downvote_alter_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
