# Generated by Django 4.2.11 on 2024-05-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_post_community_delete_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
