# Generated by Django 4.2.11 on 2024-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_post_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='positions',
            field=models.CharField(default='["Pro", "Against"]', max_length=1000),
        ),
    ]
