# Generated by Django 4.2.11 on 2024-05-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_post_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='position',
            field=models.CharField(default='Pro', max_length=1000),
        ),
    ]
